image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - set /gradlew
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации

notifications:
  - provider: Email
    # Список адресов
    to:
      - zybu@live.ru
    # Отправлять ли письмо в случае успеха?
    on_build_success: true
    # Отправлять ли письмо в случае провала?
    on_build_failure: false
    # Отправлять ли письмо когда статус изменился?
    on_build_status_changed: false